activation_fn: "Tanh"
net_arch: [256, 256, 256]
ortho_init: false
log_std_init: -1.0

learning_rate: 3e-4
n_steps: 2048
batch_size: 64
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: false
